[0m16:59:00.050907 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f0f620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a1f750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a1f890>]}


============================== 16:59:00.053794 | f9085979-206e-4a16-858b-10251df5396b ==============================
[0m16:59:00.053794 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:59:00.054061 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/leonardonunes/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init sales_analytics', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:59:00.062991 [info ] [MainThread]: Creating dbt configuration folder at /Users/leonardonunes/.dbt
[0m16:59:00.063725 [debug] [MainThread]: Starter project path: /Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m16:59:00.066598 [info ] [MainThread]: 
Your new dbt project "sales_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:59:00.066727 [info ] [MainThread]: Setting up your profile.
[0m16:59:54.623126 [error] [MainThread]: Encountered an error:
list index out of range
[0m16:59:54.631907 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "/Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/leonardonunes/Documents/projects/dbt-sales/venv/lib/python3.13/site-packages/dbt/task/init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

[0m16:59:54.650477 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 54.6306, "process_in_blocks": "0", "process_kernel_time": 0.084971, "process_mem_max_rss": "105578496", "process_out_blocks": "0", "process_user_time": 0.537408}
[0m16:59:54.651063 [debug] [MainThread]: Command `dbt init` failed at 16:59:54.650977 after 54.63 seconds
[0m16:59:54.651809 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b083e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ac3770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088ba690>]}
[0m16:59:54.652315 [debug] [MainThread]: Flushing usage events
[0m16:59:55.301929 [debug] [MainThread]: An error was encountered while trying to flush usage events
